### ISSUE TITLE
Sync with AUR

### ISSUE THREAD

**Issue by Vincent43** [TheRojam/AUR-yubikey-full-disk-encryption#2]
@TheRojam hi, could you sync recent changes with [AUR](https://aur.archlinux.org/packages/yubikey-full-disk-encryption-git/)? That would make AUR package finally working.

**Comment by TheRojam** [comment]
I had the recent changes locally and here. I was working on a testing docker for it.
But i pushed it now w/o testing to [AUR](https://aur.archlinux.org/packages/yubikey-full-disk-encryption-git/).
Should be in sync now.

**Comment by Vincent43** [comment]
H, it's weird as AUR doesn't show any updates: https://aur.archlinux.org/packages/yubikey-full-disk-encryption-git/

**Comment by TheRojam** [comment]
idk what the problem was. but take a look there. should be updated now

**Comment by Vincent43** [comment]
@TheRojam but [those](https://aur.archlinux.org/cgit/aur.git/commit/?h=yubikey-full-disk-encryption-git&id=bfcb289c21f510f171bb11af9ee7c54f202944d0) aren't the changes I made in https://github.com/TheRojam/AUR-yubikey-full-disk-encryption/commit/8ad8459af3f590b3eb967d7c5c2f923a819ade71 . The PKGBUILD is still broken. Could you upload to AUR exact [.SRCINFO](https://github.com/TheRojam/AUR-yubikey-full-disk-encryption/blob/master/.SRCINFO) and [PKGBUILD](https://github.com/TheRojam/AUR-yubikey-full-disk-encryption/blob/master/PKGBUILD) from this repo?

**Comment by Vincent43** [comment]
It finally works after last update, thank you.
